In [58]:
import pandas as pd

Sub = pd.read_csv("SPD.csv")
print(Sub.to_string())

      age  monthly_income  website_visits  time_spent_minutes  previous_purchases  is_student country device_type  purchased
0      56     1638.553977               8           16.728722                   1           0      TR     Desktop          1
1      46     2499.096428               6           13.626011                   2           0      NL      Tablet          1
2      32     3727.544600               9            6.122760                   2           0      NL      Mobile          0
3      60     4867.453423              10            9.321937                   5           1      NL      Mobile          1
4      25     2703.895072              12           12.331889                   6           0      TR      Mobile          1
5      38     3639.006309               5           16.347099                   4           0      NL      Tablet          1
6      56     2175.089153               9           21.909120                   3           0      FR      Mobile          1
7      36     5473.049374               7           14.488521                   1           1      FR      Mobile          1
8      40     6575.996671              11           20.201623                   3           0      TR      Mobile          0
9      28     6413.923787               9           22.244138                   2           0      TR      Tablet          1
10     28     5447.469326               7           12.136220                   2           0      DE     Desktop          1
11     41     5293.764936               7            7.982653                   1           1      TR      Mobile          1
12     53     1000.000000              11           15.187064                   4           0      DE      Mobile          1
13     57     4265.759848              18            8.308138                   5           1      NL      Tablet          1
14     41     3255.861065              11           24.086885                   1           0      DE      Tablet          1
15     20     5320.699542               5           20.830316                   3           1      TR     Desktop          0
16     39     1000.000000               6           22.045081                   2           0      DE      Mobile          1
17     19     4289.451554               5            6.350542                   4           0      NL      Tablet          1
18     41     3678.334324              11           13.182442                   1           0      DE      Tablet          1
19     61     5677.644899               5           15.266472                   4           0      NL      Tablet          1
20     47     6321.980581               3           17.008735                   0           0      TR     Desktop          0
21     55     2606.730974               7           13.194924                   5           1      FR      Tablet          1
22     19     2674.434346              12            2.015087                   4           0      NL     Desktop          1
23     38     4345.744932              11           17.312113                   3           0      FR      Tablet          1
24     50     6600.644037               9           23.834411                   3           0      DE     Desktop          1
25     29     4090.217016               9           25.049807                   3           1      DE      Mobile          1
26     39     2081.257877              10           13.671898                   3           0      FR      Tablet          1
27     61     3091.197331               6           15.392660                   3           1      DE      Mobile          1
28     42     4303.996247              14            9.969267                   2           1      TR     Desktop          1
29     44     4360.303643              12           15.397355                   3           0      DE      Tablet          0
30     59     2943.868547              12           12.855724                   3           1      TR     Desktop          1
31     45     3061.313959               8           12.408437                   4           1      TR      Mobile          1
32     33     2527.648008               5            7.517547                   2           1      DE     Desktop          0
33     32     5711.756776              14           22.704774                   5           0      TR     Desktop          1
34     64     2747.837231               5           13.782940                   1           0      FR      Mobile          1
35     61     3302.808694              15           12.608052                   2           0      NL      Tablet          1
36     20     3260.120625               7           16.121886                   1           0      NL     Desktop          1
37     54     1591.064129               8           12.106013                   7           0      TR     Desktop          1
38     24     2704.877043              12            4.513954                   1           0      NL      Tablet          1
39     38     5842.206399              15           21.527549                   6           0      NL      Tablet          1
40     26     2186.068237              10           15.172367                   2           0      NL      Mobile          0
41     56     2554.536547              14           18.936822                   3           1      DE     Desktop          1
42     35     2001.181339               6           15.968058                   3           1      FR      Mobile          0
43     21     3864.082660              10           19.743716                   4           1      NL     Desktop          1
44     42     6828.215082              16           18.510034                   3           1      NL      Tablet          1
45     31     3800.958668              10            3.910364                   2           1      NL      Tablet          1
46     26     4100.143188              10           17.241529                   4           1      NL     Desktop          1
47     43     2806.829146               5           10.534505                   3           0      NL      Tablet          1
48     19     3907.572933               8           10.512147                   1           0      TR     Desktop          1
49     37     5843.575460               9            6.550681                   1           0      TR      Tablet          1
50     45     4214.364081               6           24.042047                   5           0      DE     Desktop          1
51     64     7197.655123              13           14.318352                   3           0      NL      Tablet          1
52     24     5889.219568              10           12.918940                   5           1      FR      Tablet          1
53     61     3870.525482               9           11.172288                   1           0      DE     Desktop          1
54     25     3841.318187              15           26.736125                   1           0      FR      Tablet          1
55     64     6446.384706              12           20.066477                   5           1      NL     Desktop          1
56     52     4205.988364               9            2.988127                   1           1      NL      Tablet          0
57     31     6113.382340               9           21.820494                   4           1      FR      Tablet          1
58     34     7004.361010               8           10.406041                   2           1      DE     Desktop          1
59     53     3693.670948               9           18.287393                   8           0      FR     Desktop          1
60     57     4527.933049              15           12.783201                   3           1      NL      Mobile          0
61     21     5470.006277              13            6.324219                   3           1      FR      Mobile          1
62     19     5151.250059              12           12.423948                   6           0      DE      Tablet          1
63     23     5140.736099              11           16.205859                   2           0      DE      Mobile          1
64     59     1999.789259               7           16.286942                   4           1      NL      Tablet          1
65     21     2727.374908              12           13.248603                   3           0      FR      Mobile          1
66     46     3257.099469              13           15.266562                   5           0      NL      Mobile          1
67     35     5821.631205               9           15.661448                   1           1      NL     Desktop          1
68     43     2146.937639              10           19.562850                   3           1      TR      Tablet          1
69     61     6284.840061              11           21.553368                   5           1      NL     Desktop          1
70     51     5169.751171              11           15.009346                   2           0      DE     Desktop          1
71     27     5731.345337               8            8.382002                   4           1      FR      Mobile          1
72     53     2605.700384              11           18.201080                   4           0      FR     Desktop          1
73     31     4108.453544               8           18.414791                   1           0      NL      Mobile          1
74     48     4448.414179               8           19.458297                   3           0      DE      Mobile          0
75     32     4382.450503               5           10.204013                   6           1      DE      Tablet          1
76     25     4443.486101              13           19.032789                   4           0      FR      Tablet          0
77     31     3585.210279              17           16.581841                   2           0      FR      Tablet          1
78     40     4202.810622              23           17.898635                   5           0      DE     Desktop          1
79     57     5550.345933              12           11.173809                   2           1      TR      Tablet          1
80     38     2250.231537               6            5.622010                   7           1      NL     Desktop          1
81     33     6320.575178               8            8.185858                   4           0      DE      Tablet          1
82     62     5472.848435              10           19.416140                   6           0      NL      Mobile          1
83     35     2552.197161               7           23.557871                   1           0      DE     Desktop          1
84     64     4575.754065              13           18.901497                   1           1      FR      Tablet          1
85     41     5352.248164              11            8.872805                   2           0      DE      Tablet          0
86     43     2147.060014               9           14.781012                   0           0      DE     Desktop          1
87     42     4062.967650               9           16.459932                   2           0      NL      Mobile          1
88     62     3882.227049              10           15.222266                   2           0      FR     Desktop          1
89     58     3031.629186              10           15.794026                   1           0      FR      Tablet          1
90     46     4138.535255               8            9.678879                   3           0      TR      Tablet          0
91     32     3099.570136              14            7.545567                   4           1      TR      Tablet          0
92     62     6061.460603              18           10.091017                   0           0      DE      Mobile          1
93     18     3060.033518               7            8.777120                   5           1      FR      Tablet          1
94     42     5187.968410               6           15.570762                   5           1      NL     Desktop          0
95     24     1516.920419              11           16.157064                   7           1      NL      Tablet          0
96     26     3757.285294               9            8.118701                   2           0      DE      Mobile          1
97     41     4018.466736              11           14.579360                   3           0      TR      Mobile          1
98     18     3708.563424               6           24.227321                   1           1      NL     Desktop          1
99     61     3405.522554               5           15.711419                   3           0      NL      Tablet          1
100    25     2998.727462              14           12.845879                   3           0      NL      Tablet          1
101    41     5131.811170               5           19.338188                   2           0      FR      Mobile          1
102    28     5499.186783              14           26.885685                   6           1      NL      Mobile          1
103    34     3876.758671               8           16.038261                   2           1      NL     Desktop          0
104    25     2355.043738              11           12.033705                   5           0      DE     Desktop          0
105    52     6690.923997              10           15.587079                   2           0      FR      Tablet          1
106    52     2680.303851               9           21.916231                   2           0      NL     Desktop          0
107    50     1810.866612               9           14.628348                   5           0      FR     Desktop          1
108    22     1000.000000              12           15.167497                   1           1      DE      Mobile          1
109    59     4149.177845               8           22.089541                   3           0      FR      Mobile          1
110    56     3673.875422               7           15.565407                   2           0      DE      Mobile          1
111    58     5546.434974              15           23.601260                   3           0      DE     Desktop          0
112    45     4916.626845               9            8.013805                   5           1      DE      Mobile          1
113    24     4435.301837               7           17.288884                   1           0      DE      Mobile          1
114    26     3592.949207              11           24.874707                   0           0      DE     Desktop          1
115    25     5664.965908              11           27.297721                   5           0      NL      Mobile          1
116    29     6801.084853              12           12.943852                   4           1      TR      Mobile          1
117    51     5513.468799              10           13.673933                   6           0      TR      Tablet          1
118    50     3304.702554              15           24.712551                   4           0      TR     Desktop          1
119    40     5172.348331              13           13.277967                   3           0      NL      Tablet          1
120    41     3396.865412               6           12.419629                   7           0      DE      Mobile          1
121    54     2342.399026              11           12.519394                   0           0      TR      Tablet          1
122    52     2651.441407              12           10.586661                   1           0      TR      Mobile          1
123    61     3462.732394              11            9.663937                   1           1      NL     Desktop          0
124    57     4155.939518               7           14.060223                   4           1      FR      Mobile          1
125    39     7090.871729              12            6.859917                   0           1      TR      Mobile          1
126    44     2677.465787               7           11.989459                   3           0      DE      Mobile          1
127    52     5985.232735               8           22.877146                   1           0      TR     Desktop          1
128    18     3524.110672              10           19.450560                   3           1      FR      Tablet          1
129    52     1000.000000              12           12.203980                   3           1      FR      Tablet          1
130    54     3241.410996               7           16.316384                   1           1      TR     Desktop          0
131    64     5765.045490               6           14.546817                   3           1      DE     Desktop          1
132    31     4517.004279               7           11.250946                   3           0      NL      Tablet          0
133    20     4606.676798              11            3.499101                   2           0      NL      Tablet          1
134    18     5992.756013              10           10.554039                   3           0      DE      Tablet          1
135    22     2445.495567              12           13.497948                   4           0      DE      Mobile          1
136    43     2422.374355               7           27.513738                   1           1      FR      Mobile          1
137    31     1000.000000              16           18.144401                   5           0      NL      Mobile          1
138    56     5315.623107               3           14.522238                   3           0      NL      Mobile          0
139    44     4843.726350               9           17.550156                   8           1      FR     Desktop          1
140    26     5085.949779              13           16.279274                   1           0      NL     Desktop          1
141    32     2225.483164              10           11.531842                   3           0      NL      Mobile          1
142    32     1593.626566               7           14.728365                   4           0      DE      Mobile          1
143    43     2020.572537              11           13.255835                   3           0      FR      Mobile          1
144    59     2616.141591              17            7.441237                   7           0      DE      Tablet          1
145    30     6330.938363              13           12.214466                   4           0      NL     Desktop          1
146    49     5500.190086               3           14.531669                   3           1      DE     Desktop          1
147    56     3312.669039               7           17.251236                   1           0      DE      Tablet          1
148    49     4448.877990               8           15.185736                   4           1      NL     Desktop          1
149    21     2982.456631              11           19.851668                   5           0      TR     Desktop          1
150    47     4546.419641               9           14.013191                   4           1      TR     Desktop          0
151    54     2292.856393              15           21.507753                   3           0      TR      Tablet          1
152    40     5125.377169              12           16.030000                   4           0      DE      Tablet          1
153    56     2725.445054               5           17.364910                   1           0      TR     Desktop          0
154    62     5208.872543               9           16.460098                   4           1      NL      Tablet          1
155    32     3358.865638              14           12.639076                   3           0      TR      Tablet          1
156    60     2814.886070               6           18.290933                   4           0      NL      Tablet          1
157    46     6419.495076              12           12.096224                   2           0      DE      Mobile          1
158    53     4265.419277               6           10.266446                   1           0      DE     Desktop          1

In [59]:
Sub.head()

,age,monthly_income,website_visits,time_spent_minutes,previous_purchases,is_student,country,device_type,purchased
0,56,1638.553977,8,16.728722,1,0,TR,Desktop,1
1,46,2499.096428,6,13.626011,2,0,NL,Tablet,1
2,32,3727.544600,9,6.122760,2,0,NL,Mobile,0
3,60,4867.453423,10,9.321937,5,1,NL,Mobile,1
4,25,2703.895072,12,12.331889,6,0,TR,Mobile,1

In [60]:
Sub.tail()

,age,monthly_income,website_visits,time_spent_minutes,previous_purchases,is_student,country,device_type,purchased
9995,33,6017.579566,6,9.049433,5,0,NL,Desktop,0
9996,29,5263.230651,6,20.253556,2,0,NL,Mobile,1
9997,18,4185.740620,7,17.508512,5,1,DE,Mobile,1
9998,25,1911.611069,11,10.865050,4,1,TR,Mobile,0
9999,30,4498.570557,15,16.618200,2,0,TR,Tablet,1

In [61]:
Sub.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   age                 10000 non-null  int64
 1   monthly_income      10000 non-null  float64
 2   website_visits      10000 non-null  int64
 3   time_spent_minutes  10000 non-null  float64
 4   previous_purchases  10000 non-null  int64
 5   is_student          10000 non-null  int64
 6   country             10000 non-null  str
 7   device_type         10000 non-null  str
 8   purchased           10000 non-null  int64
dtypes: float64(2), int64(5), str(2)
memory usage: 703.3 KB

In [62]:
Sub.isnull().sum()

age                   0
monthly_income        0
website_visits        0
time_spent_minutes    0
previous_purchases    0
is_student            0
country               0
device_type           0
purchased             0
dtype: int64

In [63]:
Sub.describe()

,age,monthly_income,website_visits,time_spent_minutes,previous_purchases,is_student,purchased
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,41.054000,4011.548809,10.038500,15.031669,3.009900,0.296900,0.793200
std,13.484104,1467.782573,3.197912,5.010769,1.723281,0.456915,0.405031
min,18.000000,1000.000000,0.000000,1.000000,0.000000,0.000000,0.000000
25%,30.000000,2974.139231,8.000000,11.700613,2.000000,0.000000,1.000000
50%,41.000000,3996.377858,10.000000,15.018620,3.000000,0.000000,1.000000
75%,53.000000,5005.978546,12.000000,18.364640,4.000000,1.000000,1.000000
max,64.000000,9399.200171,27.000000,32.871504,10.000000,1.000000,1.000000

In [64]:
Sub

,age,monthly_income,website_visits,time_spent_minutes,previous_purchases,is_student,country,device_type,purchased
0,56,1638.553977,8,16.728722,1,0,TR,Desktop,1
1,46,2499.096428,6,13.626011,2,0,NL,Tablet,1
2,32,3727.544600,9,6.122760,2,0,NL,Mobile,0
3,60,4867.453423,10,9.321937,5,1,NL,Mobile,1
4,25,2703.895072,12,12.331889,6,0,TR,Mobile,1
...,...,...,...,...,...,...,...,...,...
9995,33,6017.579566,6,9.049433,5,0,NL,Desktop,0
9996,29,5263.230651,6,20.253556,2,0,NL,Mobile,1
9997,18,4185.740620,7,17.508512,5,1,DE,Mobile,1
9998,25,1911.611069,11,10.865050,4,1,TR,Mobile,0
9999,30,4498.570557,15,16.618200,2,0,TR,Tablet,1

#1️⃣ Convert country to Uppercase


we standardize the country column by converting all values to uppercase?

In [65]:
Sub['country'] = Sub['country'].str.upper()

This ensures consistency in text formatting and prevents issues caused by mixed case values

#2️⃣ Create Annual Income Column

we create a new column annual_income from monthly_income?

In [66]:
Sub['annual_income'] = Sub['monthly_income'] * 12

This derives yearly income from monthly income, which may be more useful for financial analysis

#3️⃣ Create High Engagement Flag

we identify users with above-average engagement?

In [67]:
Sub['high_engagement'] = Sub['time_spent_minutes'] > Sub['time_spent_minutes'].mean()

This creates a Boolean column identifying users who spend more time than average on the platform.

#4️⃣ Create Frequent Visitor Column

we classify users as frequent visitors based on website visits?

In [68]:
Sub['frequent_visitor'] = Sub['website_visits'] > 10

#5️⃣ Rename Column

we rename time_spent_minutes to time_spent for simplicity?

In [69]:
Sub = Sub.rename(columns={'time_spent_minutes': 'time_spent'})

Sub = Sub.rename(columns={'time_spent_minutes': 'time_spent'})

#6️⃣ Convert device_type to Uppercase

we standardize the device_type column by converting values to uppercase?

In [70]:
Sub['device_type'] = Sub['device_type'].str.upper()

This ensures uniform formatting and avoids inconsistencies in categorical data.

#7️⃣ Create Income per Age Ratio
we create a new column measuring income relative to age?

In [71]:
Sub['income_per_age'] = Sub['monthly_income'] / Sub['age']

This derived feature may help analyze financial capacity adjusted for age.

#8️⃣ Create Returning Customer Flag
identify returning customers based on previous purchases?

In [72]:
Sub['returning_customer'] = Sub['previous_purchases'] > 0

This categorizes users as new or returning customers, useful for behavioral analysis.

9️⃣ Remove Extra Spaces from country
clean the country column by removing leading/trailing spaces?

In [73]:
Sub['country'] = Sub['country'].str.strip()

Removing whitespace prevents duplicate-like entries caused by hidden spaces.

🔟 Create Total Engagement Column
create a combined engagement metric using visits and time spent?

In [74]:
Sub['total_engagement'] = Sub['website_visits'] + Sub['time_spent']

This creates a composite metric representing overall user engagement.

In [75]:
Sub

,age,monthly_income,website_visits,time_spent,previous_purchases,is_student,country,device_type,purchased,annual_income,high_engagement,frequent_visitor,income_per_age,returning_customer,total_engagement
0,56,1638.553977,8,16.728722,1,0,TR,DESKTOP,1,19662.647726,True,False,29.259892,True,24.728722
1,46,2499.096428,6,13.626011,2,0,NL,TABLET,1,29989.157140,False,False,54.328183,True,19.626011
2,32,3727.544600,9,6.122760,2,0,NL,MOBILE,0,44730.535205,False,False,116.485769,True,15.122760
3,60,4867.453423,10,9.321937,5,1,NL,MOBILE,1,58409.441078,False,False,81.124224,True,19.321937
4,25,2703.895072,12,12.331889,6,0,TR,MOBILE,1,32446.740862,False,True,108.155803,True,24.331889
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,33,6017.579566,6,9.049433,5,0,NL,DESKTOP,0,72210.954793,False,False,182.350896,True,15.049433
9996,29,5263.230651,6,20.253556,2,0,NL,MOBILE,1,63158.767810,True,False,181.490712,True,26.253556
9997,18,4185.740620,7,17.508512,5,1,DE,MOBILE,1,50228.887436,True,False,232.541146,True,24.508512
9998,25,1911.611069,11,10.865050,4,1,TR,MOBILE,0,22939.332827,False,True,76.464443,True,21.865050
9999,30,4498.570557,15,16.618200,2,0,TR,TABLET,1,53982.846685,True,True,149.952352,True,31.618200

In [77]:
Sub.to_csv("Subscription.csv", index=True)  
#to save as a new CSV file